version: "3"

services:
  web:
    build: .
    networks:
      - cassandra-net
      - grafana-net
    ports:
      - "8000:8000"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - grafana-net

  graphite_statsd:
    image: graphiteapp/docker-graphite-statsd:latest
    container_name: graphite-statsd
    ports:
      - '8125:8125/udp'
      - '2003:2003'
      - '80:80'
    networks:
      - grafana-net

networks:
  grafana-net:
  cassandra-net:

